/*
Copyright 2021 the Apache Pinot Kubernetes Operator authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"
	"time"

	v1alpha1 "github.com/spaghettifunk/pinot-operator/api/pinot/v1alpha1"
	scheme "github.com/spaghettifunk/pinot-operator/pkg/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// PinotsGetter has a method to return a PinotInterface.
// A group's client should implement this interface.
type PinotsGetter interface {
	Pinots(namespace string) PinotInterface
}

// PinotInterface has methods to work with Pinot resources.
type PinotInterface interface {
	Create(ctx context.Context, pinot *v1alpha1.Pinot, opts v1.CreateOptions) (*v1alpha1.Pinot, error)
	Update(ctx context.Context, pinot *v1alpha1.Pinot, opts v1.UpdateOptions) (*v1alpha1.Pinot, error)
	UpdateStatus(ctx context.Context, pinot *v1alpha1.Pinot, opts v1.UpdateOptions) (*v1alpha1.Pinot, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v1alpha1.Pinot, error)
	List(ctx context.Context, opts v1.ListOptions) (*v1alpha1.PinotList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.Pinot, err error)
	PinotExpansion
}

// pinots implements PinotInterface
type pinots struct {
	client rest.Interface
	ns     string
}

// newPinots returns a Pinots
func newPinots(c *PinotV1alpha1Client, namespace string) *pinots {
	return &pinots{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the pinot, and returns the corresponding pinot object, and an error if there is any.
func (c *pinots) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.Pinot, err error) {
	result = &v1alpha1.Pinot{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("pinots").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of Pinots that match those selectors.
func (c *pinots) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.PinotList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha1.PinotList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("pinots").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested pinots.
func (c *pinots) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("pinots").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a pinot and creates it.  Returns the server's representation of the pinot, and an error, if there is any.
func (c *pinots) Create(ctx context.Context, pinot *v1alpha1.Pinot, opts v1.CreateOptions) (result *v1alpha1.Pinot, err error) {
	result = &v1alpha1.Pinot{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("pinots").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(pinot).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a pinot and updates it. Returns the server's representation of the pinot, and an error, if there is any.
func (c *pinots) Update(ctx context.Context, pinot *v1alpha1.Pinot, opts v1.UpdateOptions) (result *v1alpha1.Pinot, err error) {
	result = &v1alpha1.Pinot{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("pinots").
		Name(pinot.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(pinot).
		Do(ctx).
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *pinots) UpdateStatus(ctx context.Context, pinot *v1alpha1.Pinot, opts v1.UpdateOptions) (result *v1alpha1.Pinot, err error) {
	result = &v1alpha1.Pinot{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("pinots").
		Name(pinot.Name).
		SubResource("status").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(pinot).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the pinot and deletes it. Returns an error if one occurs.
func (c *pinots) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("pinots").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *pinots) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("pinots").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched pinot.
func (c *pinots) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.Pinot, err error) {
	result = &v1alpha1.Pinot{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("pinots").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
