/*
Copyright 2021 the Apache Pinot Kubernetes Operator authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "github.com/spaghettifunk/pinot-operator/api/pinot/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakePinots implements PinotInterface
type FakePinots struct {
	Fake *FakePinotV1alpha1
	ns   string
}

var pinotsResource = schema.GroupVersionResource{Group: "pinot", Version: "v1alpha1", Resource: "pinots"}

var pinotsKind = schema.GroupVersionKind{Group: "pinot", Version: "v1alpha1", Kind: "Pinot"}

// Get takes name of the pinot, and returns the corresponding pinot object, and an error if there is any.
func (c *FakePinots) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.Pinot, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(pinotsResource, c.ns, name), &v1alpha1.Pinot{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Pinot), err
}

// List takes label and field selectors, and returns the list of Pinots that match those selectors.
func (c *FakePinots) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.PinotList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(pinotsResource, pinotsKind, c.ns, opts), &v1alpha1.PinotList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.PinotList{ListMeta: obj.(*v1alpha1.PinotList).ListMeta}
	for _, item := range obj.(*v1alpha1.PinotList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested pinots.
func (c *FakePinots) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(pinotsResource, c.ns, opts))

}

// Create takes the representation of a pinot and creates it.  Returns the server's representation of the pinot, and an error, if there is any.
func (c *FakePinots) Create(ctx context.Context, pinot *v1alpha1.Pinot, opts v1.CreateOptions) (result *v1alpha1.Pinot, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(pinotsResource, c.ns, pinot), &v1alpha1.Pinot{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Pinot), err
}

// Update takes the representation of a pinot and updates it. Returns the server's representation of the pinot, and an error, if there is any.
func (c *FakePinots) Update(ctx context.Context, pinot *v1alpha1.Pinot, opts v1.UpdateOptions) (result *v1alpha1.Pinot, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(pinotsResource, c.ns, pinot), &v1alpha1.Pinot{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Pinot), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakePinots) UpdateStatus(ctx context.Context, pinot *v1alpha1.Pinot, opts v1.UpdateOptions) (*v1alpha1.Pinot, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(pinotsResource, "status", c.ns, pinot), &v1alpha1.Pinot{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Pinot), err
}

// Delete takes name of the pinot and deletes it. Returns an error if one occurs.
func (c *FakePinots) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(pinotsResource, c.ns, name), &v1alpha1.Pinot{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakePinots) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(pinotsResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.PinotList{})
	return err
}

// Patch applies the patch and returns the patched pinot.
func (c *FakePinots) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.Pinot, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(pinotsResource, c.ns, name, pt, data, subresources...), &v1alpha1.Pinot{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Pinot), err
}
