apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: pinot-system
images:
- name: davideberdin/pinot-operator-dev
  newName: davideberdin/pinot-operator
  newTag: latest
resources:
- ../namespace/base/
- ../crd/
- ../rbac/
- ../manager/