# permissions for end users to view pinots.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: pinot-viewer-role
rules:
- apiGroups:
  - cluster.spaghettifunk.io
  resources:
  - pinots
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - cluster.spaghettifunk.io
  resources:
  - pinots/status
  verbs:
  - get
