# permissions for end users to edit pinots.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: pinot-editor-role
rules:
- apiGroups:
  - cluster.spaghettifunk.io
  resources:
  - pinots
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cluster.spaghettifunk.io
  resources:
  - pinots/status
  verbs:
  - get
