
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  - events
  - poddisruptionbudgets
  - services
  - statefulsets
  verbs:
  - create
  - delete
  - get
  - list
  - update
  - watch
- apiGroups:
  - apps
  - policy
  resources:
  - deployments
  - poddisruptionbudgets
  verbs:
  - '*'
- apiGroups:
  - operators
  resources:
  - configmaps
  - poddisruptionbudgets
  - secrets
  - services
  - statefulsets
  verbs:
  - create
  - delete
  - get
  - list
  - update
  - watch
- apiGroups:
  - operators.apache.io
  resources:
  - pinots
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - operators.apache.io
  resources:
  - pinots/status
  verbs:
  - get
  - patch
  - update
