# permissions for end users to edit schemas.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: schema-editor-role
rules:
- apiGroups:
  - operators.apache.io
  resources:
  - schemas
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - operators.apache.io
  resources:
  - schemas/status
  verbs:
  - get
