# permissions for end users to view schemas.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: schema-viewer-role
rules:
- apiGroups:
  - pinot.apache.io
  resources:
  - schemas
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - pinot.apache.io
  resources:
  - schemas/status
  verbs:
  - get
