# permissions for end users to edit tables.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: table-editor-role
rules:
- apiGroups:
  - operators.apache.io
  resources:
  - tables
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - operators.apache.io
  resources:
  - tables/status
  verbs:
  - get
