/*
Copyright 2021 the Apache Pinot Kubernetes Operator authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by informer-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"
	time "time"

	pinotv1alpha1 "github.com/spaghettifunk/pinot-operator/api/pinot/v1alpha1"
	versioned "github.com/spaghettifunk/pinot-operator/pkg/client/clientset/versioned"
	internalinterfaces "github.com/spaghettifunk/pinot-operator/pkg/client/informers/externalversions/internalinterfaces"
	v1alpha1 "github.com/spaghettifunk/pinot-operator/pkg/client/listers/pinot/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// PinotInformer provides access to a shared informer and lister for
// Pinots.
type PinotInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1alpha1.PinotLister
}

type pinotInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewPinotInformer constructs a new informer for Pinot type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewPinotInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredPinotInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredPinotInformer constructs a new informer for Pinot type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredPinotInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.PinotV1alpha1().Pinots(namespace).List(context.TODO(), options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.PinotV1alpha1().Pinots(namespace).Watch(context.TODO(), options)
			},
		},
		&pinotv1alpha1.Pinot{},
		resyncPeriod,
		indexers,
	)
}

func (f *pinotInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredPinotInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *pinotInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&pinotv1alpha1.Pinot{}, f.defaultInformer)
}

func (f *pinotInformer) Lister() v1alpha1.PinotLister {
	return v1alpha1.NewPinotLister(f.Informer().GetIndexer())
}
